version: '2'

services:

  tomcat:
    build:
        context: ./tomcat-docker
    container_name: tomcat
    ports:
      - 8081:8080

  jenkins:
    build:
        context: ./jenkins-docker
    container_name: jenkins
    volumes:
      - ./jenkins-docker/jobs:/var/jenkins_home/jobs
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
    ports:
      - 8080:8080

