package test.java;

import static org.junit.Assert.*;

import org.junit.jupiter.api.Test;

import main.java.Library;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//import org.junit.Test;
//import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
